// Motor 02, Intent Engine, fase 1.
// Nesta fase as árvores de intenção são curadas por humano, exatamente como a
// especificação exige: nenhuma árvore entra no diagnóstico sem revisão.
// Quando o Search Console e a busca interna estiverem instrumentados, os números
// de demanda passam a vir das tabelas, e a estrutura destes objetos não muda.

import type { IntentCluster } from "./types";

export const INTENT_CLUSTERS: IntentCluster[] = [
  {
    id: "recuperar-bitcoin",
    rootQuery: "como recuperar bitcoin perdido",
    rootLabel: "Recuperação de Bitcoin após perda de acesso",
    silo: "Segurança & Autocustódia",
    stage: "Blindar",
    kind: "diagnostico",
    riskLevel: "alto",
    guards: ["GUARD-RISK-01", "GUARD-RISK-02", "GUARD-YMYL-01"],
    requiredAngle:
      "Separar o que ainda é recuperável do que já é definitivo. Proibido sugerir que uma chave perdida pode ser recuperada.",
    suggestedTitle: "Recuperação de Bitcoin: o que é possível e o que não é",
    suggestedPath: "/autocustodia/recuperacao-de-bitcoin",
    cta: "Antes de tentar recuperar qualquer coisa, descubra se você perdeu o acesso ou apenas o caminho até a sua carteira.",
    demand: {
      distinctQueries: 12,
      impressions: 4800,
      internalSearches: 18,
      humanQuestions: 4,
      trendIndex: 62,
      sources: ["estimativa"],
    },
    children: [
      {
        id: "recuperar-bitcoin.perdi-a-seed",
        label: "Perdi a seed",
        question: "Perdi as 12 palavras. Ainda existe alguma coisa que eu possa fazer?",
        kind: "diagnostico",
        stage: "Blindar",
        riskLevel: "alto",
        terms: ["seed", "perdi", "palavras", "frase", "recuperacao", "backup", "acesso"],
      },
      {
        id: "recuperar-bitcoin.passphrase",
        label: "Esqueci a passphrase",
        question: "Tenho a seed, mas esqueci a passphrase. Dá para chegar na carteira?",
        kind: "diagnostico",
        stage: "Blindar",
        riskLevel: "alto",
        terms: ["passphrase", "senha", "esqueci", "palavra", "extra", "25", "seed"],
      },
      {
        id: "recuperar-bitcoin.carteira-nao-abre",
        label: "A carteira não abre",
        question: "A carteira não abre ou não mostra saldo. Perdi os bitcoins?",
        kind: "procedimento",
        stage: "Operar",
        riskLevel: "medio",
        terms: ["carteira", "nao", "abre", "saldo", "sumiu", "restaurar", "software", "wallet"],
      },
      {
        id: "recuperar-bitcoin.derivation-path",
        label: "Backup existe, mas não funciona",
        question: "Restaurei o backup e a carteira aparece vazia. O que é derivation path?",
        kind: "procedimento",
        stage: "Operar",
        riskLevel: "medio",
        terms: ["derivation", "path", "backup", "restaurar", "vazia", "xpub", "formato", "bip"],
      },
      {
        id: "recuperar-bitcoin.endereco-errado",
        label: "Enviei para o endereço errado",
        question: "Mandei bitcoin para o endereço errado. Tem como reverter?",
        kind: "diagnostico",
        stage: "Operar",
        riskLevel: "alto",
        terms: ["endereco", "errado", "enviei", "transacao", "reverter", "irreversivel", "cancelar"],
      },
      {
        id: "recuperar-bitcoin.exchange",
        label: "Perdi acesso à exchange",
        question: "Perdi acesso à conta da corretora. Como recupero meus bitcoins?",
        kind: "legal",
        stage: "Operar",
        riskLevel: "medio",
        terms: ["exchange", "corretora", "conta", "bloqueada", "custodia", "suporte", "kyc"],
      },
      {
        id: "recuperar-bitcoin.golpe",
        label: "Fui vítima de golpe",
        question: "Caí em um golpe e transferi bitcoin. Existe caminho legal?",
        kind: "legal",
        stage: "Blindar",
        riskLevel: "alto",
        terms: ["golpe", "fraude", "roubo", "estelionato", "boletim", "policia", "rastreio"],
      },
      {
        id: "recuperar-bitcoin.seed-antiga",
        label: "Encontrei uma seed antiga",
        question: "Achei um papel com palavras. Como descubro se tem bitcoin nele?",
        kind: "procedimento",
        stage: "Operar",
        riskLevel: "medio",
        terms: ["seed", "antiga", "papel", "varredura", "carteira", "verificar", "saldo"],
      },
      {
        id: "recuperar-bitcoin.servico-recuperacao",
        label: "Serviço de recuperação",
        question: "Vale a pena contratar uma empresa de recuperação de bitcoin?",
        kind: "risco",
        stage: "Blindar",
        riskLevel: "alto",
        terms: ["servico", "empresa", "recuperacao", "contratar", "hacker", "golpe", "secundario"],
      },
    ],
  },
  {
    id: "heranca-bitcoin",
    rootQuery: "como deixar bitcoin para meus filhos",
    rootLabel: "Sucessão e herança de Bitcoin",
    silo: "Segurança & Autocustódia",
    stage: "Transmitir",
    kind: "procedimento",
    riskLevel: "alto",
    guards: ["GUARD-YMYL-01"],
    suggestedTitle: "Herança de Bitcoin: arquitetura completa de sucessão",
    demand: {
      distinctQueries: 9,
      impressions: 2600,
      internalSearches: 11,
      humanQuestions: 6,
      trendIndex: 48,
      sources: ["estimativa"],
    },
    children: [
      {
        id: "heranca-bitcoin.instrucoes",
        label: "Carta de instruções",
        question: "Como escrever instruções que meu herdeiro consiga seguir sozinho?",
        kind: "procedimento",
        stage: "Transmitir",
        riskLevel: "medio",
        terms: ["instrucoes", "carta", "herdeiro", "documento", "passo", "sucessao"],
      },
      {
        id: "heranca-bitcoin.multisig",
        label: "Multisig para sucessão",
        question: "Multisig resolve herança ou complica ainda mais?",
        kind: "decisao",
        stage: "Transmitir",
        riskLevel: "medio",
        terms: ["multisig", "quorum", "chaves", "cosigner", "heranca", "sucessao"],
      },
      {
        id: "heranca-bitcoin.inventario",
        label: "Inventário e imposto",
        question: "Bitcoin entra em inventário? Como declarar na sucessão?",
        kind: "legal",
        stage: "Transmitir",
        riskLevel: "alto",
        terms: ["inventario", "imposto", "itcmd", "declarar", "espolio", "heranca", "juridico"],
      },
      {
        id: "heranca-bitcoin.exposicao",
        label: "Risco de exposição do herdeiro",
        question: "Como transmitir sem expor o herdeiro a risco físico?",
        kind: "risco",
        stage: "Transmitir",
        riskLevel: "alto",
        terms: ["exposicao", "risco", "fisico", "sequestro", "privacidade", "herdeiro", "sigilo"],
      },
      {
        id: "heranca-bitcoin.teste",
        label: "Teste do plano",
        question: "Como testar se o plano de herança realmente funciona?",
        kind: "procedimento",
        stage: "Transmitir",
        riskLevel: "medio",
        terms: ["teste", "simulacao", "ensaio", "verificar", "plano", "recuperacao"],
      },
    ],
  },
  {
    id: "bitcoin-imposto",
    rootQuery: "como declarar bitcoin no imposto de renda",
    rootLabel: "Bitcoin e imposto de renda",
    silo: "Soberania Financeira",
    stage: "Operar",
    kind: "legal",
    riskLevel: "alto",
    guards: ["GUARD-YMYL-01"],
    demand: {
      distinctQueries: 14,
      impressions: 7100,
      internalSearches: 9,
      humanQuestions: 5,
      trendIndex: 71,
      sources: ["estimativa"],
    },
    children: [
      {
        id: "bitcoin-imposto.declarar",
        label: "Como declarar",
        question: "Onde e como declaro bitcoin na declaração anual?",
        kind: "procedimento",
        stage: "Operar",
        riskLevel: "alto",
        terms: ["declarar", "imposto", "renda", "ficha", "bens", "direitos", "receita"],
      },
      {
        id: "bitcoin-imposto.p2p",
        label: "Compra P2P e obrigações",
        question: "Comprei P2P, sem corretora. Preciso declarar do mesmo jeito?",
        kind: "legal",
        stage: "Operar",
        riskLevel: "alto",
        terms: ["p2p", "sem", "corretora", "declarar", "in", "1888", "obrigacao"],
      },
      {
        id: "bitcoin-imposto.perda",
        label: "Bitcoin perdido e imposto",
        question: "Perdi acesso à carteira. O que faço com isso na declaração?",
        kind: "legal",
        stage: "Operar",
        riskLevel: "alto",
        terms: ["perda", "perdido", "baixa", "declaracao", "acesso", "carteira", "prejuizo"],
      },
      {
        id: "bitcoin-imposto.venda",
        label: "Ganho de capital na venda",
        question: "Quanto de imposto pago ao vender bitcoin?",
        kind: "procedimento",
        stage: "Operar",
        riskLevel: "alto",
        terms: ["ganho", "capital", "venda", "aliquota", "isencao", "darf", "35"],
      },
    ],
  },
  {
    id: "comprar-bitcoin-brasil",
    rootQuery: "como comprar bitcoin no brasil passo a passo",
    rootLabel: "Primeira compra de Bitcoin no Brasil",
    silo: "Bitcoin — Fundamentos",
    stage: "Despertar",
    kind: "procedimento",
    riskLevel: "medio",
    guards: ["GUARD-YMYL-01"],
    demand: {
      distinctQueries: 21,
      impressions: 15400,
      internalSearches: 24,
      humanQuestions: 9,
      trendIndex: 84,
      sources: ["estimativa"],
    },
    children: [
      {
        id: "comprar-bitcoin-brasil.primeira-compra",
        label: "Primeira compra",
        question: "Nunca comprei. Qual é o passo a passo real?",
        kind: "procedimento",
        stage: "Despertar",
        riskLevel: "baixo",
        terms: ["comprar", "primeira", "passo", "iniciante", "comecar", "corretora", "pix"],
      },
      {
        id: "comprar-bitcoin-brasil.quanto-custa",
        label: "Quanto custa começar",
        question: "Preciso de quanto dinheiro para começar?",
        kind: "decisao",
        stage: "Despertar",
        riskLevel: "baixo",
        terms: ["quanto", "custa", "minimo", "valor", "comecar", "satoshi", "fracao"],
      },
      {
        id: "comprar-bitcoin-brasil.erros",
        label: "Erros de iniciante",
        question: "Quais erros quase todo iniciante comete?",
        kind: "risco",
        stage: "Despertar",
        riskLevel: "medio",
        terms: ["erros", "iniciante", "comuns", "evitar", "armadilha", "prejuizo"],
      },
      {
        id: "comprar-bitcoin-brasil.tirar-da-corretora",
        label: "Tirar da corretora",
        question: "Comprei. Preciso tirar da corretora agora?",
        kind: "decisao",
        stage: "Blindar",
        riskLevel: "medio",
        terms: ["sacar", "retirar", "corretora", "carteira", "autocustodia", "transferir"],
      },
    ],
  },
  {
    id: "celular-escuta",
    rootQuery: "celular escuta conversa para mostrar anuncio",
    rootLabel: "Escuta e rastreamento no celular",
    silo: "Segurança Mobile",
    stage: "Entender",
    kind: "diagnostico",
    riskLevel: "medio",
    guards: ["GUARD-STYLE-01"],
    demand: {
      distinctQueries: 11,
      impressions: 9200,
      internalSearches: 7,
      humanQuestions: 3,
      trendIndex: 77,
      sources: ["estimativa"],
    },
    children: [
      {
        id: "celular-escuta.microfone",
        label: "O microfone escuta?",
        question: "O celular escuta minha conversa pelo microfone?",
        kind: "diagnostico",
        stage: "Entender",
        riskLevel: "medio",
        terms: ["microfone", "escuta", "conversa", "anuncio", "gravacao", "permissao"],
      },
      {
        id: "celular-escuta.perfil",
        label: "Perfilamento sem microfone",
        question: "Se não é o microfone, como eles acertam tanto?",
        kind: "definicao",
        stage: "Entender",
        riskLevel: "medio",
        terms: ["perfil", "rastreamento", "dados", "anuncio", "identificador", "correlacao"],
      },
      {
        id: "celular-escuta.desligar",
        label: "Como reduzir",
        question: "O que eu desligo hoje para reduzir isso?",
        kind: "procedimento",
        stage: "Blindar",
        riskLevel: "baixo",
        terms: ["desligar", "permissao", "microfone", "anuncio", "identificador", "configuracao"],
      },
    ],
  },
  {
    id: "seguranca-seed-fisica",
    rootQuery: "como proteger a seed phrase",
    rootLabel: "Ciclo completo da seed phrase",
    silo: "Segurança & Autocustódia",
    stage: "Blindar",
    kind: "procedimento",
    riskLevel: "alto",
    guards: ["GUARD-RISK-01"],
    demand: {
      distinctQueries: 16,
      impressions: 6300,
      internalSearches: 14,
      humanQuestions: 7,
      trendIndex: 58,
      sources: ["estimativa"],
    },
    children: [
      {
        id: "seguranca-seed-fisica.geracao",
        label: "Geração",
        question: "Como a seed é gerada e o que é entropia de verdade?",
        kind: "definicao",
        stage: "Entender",
        riskLevel: "medio",
        terms: ["geracao", "entropia", "bip39", "aleatorio", "dado", "checksum"],
      },
      {
        id: "seguranca-seed-fisica.armazenamento",
        label: "Armazenamento",
        question: "Papel, aço ou metal? Onde guardo?",
        kind: "decisao",
        stage: "Blindar",
        riskLevel: "medio",
        terms: ["aco", "metal", "papel", "guardar", "armazenar", "cofre", "fogo"],
      },
      {
        id: "seguranca-seed-fisica.teste",
        label: "Teste de recuperação",
        question: "Como testar o backup sem arriscar os fundos?",
        kind: "procedimento",
        stage: "Operar",
        riskLevel: "medio",
        terms: ["teste", "recuperacao", "restaurar", "verificar", "backup", "ensaio"],
      },
      {
        id: "seguranca-seed-fisica.erro-humano",
        label: "Erro humano",
        question: "Quais erros de anotação destroem um backup?",
        kind: "risco",
        stage: "Blindar",
        riskLevel: "alto",
        terms: ["erro", "humano", "anotacao", "ordem", "palavra", "letra", "ilegivel"],
      },
      {
        id: "seguranca-seed-fisica.destruicao",
        label: "Destruição física",
        question: "Como destruir um backup antigo com segurança?",
        kind: "procedimento",
        stage: "Operar",
        riskLevel: "medio",
        terms: ["destruir", "descartar", "backup", "antigo", "queimar", "eliminar"],
      },
    ],
  },
];
